kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn -B -DskipTests clean package
      - mvn test -B
    volumes:
      - name: m2
        path: /root/.m2

  - name: archive-artifact
    image: alpine:latest
    commands:
      - sleep 60
      - mkdir -p /builds/mplayer4anime
      - cp target/mplayer4anime-*jar /builds/mplayer4anime/
    volumes:
      - name: builds
        path: /builds

volumes:
  - name: m2
    host:
      path: /m2
  - name: builds
    host:
      path: /builds