kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn -B -DskipTests clean package
      - mvn test -B
    volumes:
      - name: m2
        path: /root/.m2

volumes:
  - name: m2
    host:
      path: /m2